# Introduction to Linear Programming

Linear programming is a technique for the optimization of a linear objective function, subject to linear equality and linear inequality constraints. Linear programs are problems defined as follows.

A *linear program* or a *linear programming problem* is a problem of the following form:

\begin{equation}
  \begin{aligned}
    \mbox{optimize: } && c_1 x_1 + \dots + c_n x_n & \\
    \mbox{subject to: } 
      && a_{11} x_1 + \dots + a_{1n} x_n & \lesseqgtr b_1 \\
      && a_{21} x_1 + \dots + a_{2n} x_n & \lesseqgtr b_2 \\
      && \vdots &  \\
      && a_{m1} x_1 + \dots + a_{mn} x_n & \lesseqgtr b_m,
  \end{aligned}
  (\#eq:intro-lp)
\end{equation}
where the symbol $\lesseqgtr$ stands for $\leq$ or $=$ or $\geq$, $a_{ij}, b_i, c_j$ are real numbers, and $x_j$ are variables.

The variables $x_1, \dots, x_n$ are called *decision variables*. The linear combination $\zeta := c_1 x_1 + \dots + c_n x_n$ is called the *objective function*. Each of the equalities/inequalities $a_{i1} x_1 + \dots + a_{in} x_n \lesseqgtr b_i$ is called a *(linear) constraint*. Our goal is to either *minimize* or *maximize* the objective function subject to the constraints.

A proposal of specific values for the decision variables is called a *solution*. A solution is said to be *feasible* if it satisfies all the constraints. A feasible solution is said to be *optimal* if $\zeta$ attains the optimal value at the solution. Thus, to solve a linear program means to *find an optimal solution* to the problem. If a problem has no feasible solution, then the problem is called *infeasible*. If a problem has feasible solutions with arbitrarily large objective values then the problem is called *unbounded*.

::: {.example #lp-intro}
Example of a LP.
:::

## Standard form of a linear program
It is difficult to work with a linear program in the form described in Equation \@ref(eq:intro-lp), mainly because of the presence of all three kinds of constraints $\leq$, $=$, and $\geq$. A linear program of the following form is said to be in a *standard form*:
\begin{equation}
  \begin{aligned}
    \mbox{maximize: } && c_1 x_1 + \dots + c_n x_n & \\
    \mbox{subject to: } 
      && a_{11} x_1 + \dots + a_{1n} x_n & \leq b_1 \\
      && a_{21} x_1 + \dots + a_{2n} x_n & \leq b_2 \\
      && \vdots &  \\
      && a_{m1} x_1 + \dots + a_{mn} x_n & \leq b_m \\
      && x_1, \dots, x_n & \geq 0.
  \end{aligned}
  (\#eq:intro-standardized-lp)
\end{equation}
It is useful to think of the objective function as the *profit* function, the decision variable $x_j$ as the amount of a physical quantity of type $j$, the coefficients $c_j$ as being the profit made from selling a unit quantity of type $j$, and each constraint corresponding to the production of an intermediate quantity.

An LP in a standard form can be written more succinctly as follows.
\begin{equation}
  \begin{aligned}
    \mbox{maximize: } && c^T x & \\
    \mbox{subject to: } 
      && A x & \leq b \\
      && x & \geq 0.
  \end{aligned}
  (\#eq:intro-standardized-lp-matrix-form)
\end{equation}
where now $x$ is the vector of decision variables, $c$ and $b$ are vectors of real numbers, and $A$ is the matrix of constraint coefficients. This enables us to use tools from Linear Algebra to solve LP problems.

## Converting LP to standard form
Notice that maximizing the objective function $\zeta$ is equivalent to minimizing the negative of the objective function $-\zeta$. From now on, we will assume that we are always trying to maximize the objective function.

Two linear programs LP and LP' are said to be *equivalent* if for any feasible solution $(x_1, \dots, x_n)$ to LP, there exists a feasible solution $(x'_1, x'_2, \dots, x'_{n'})$ to LP' such that $\zeta(x_1, \dots, x_n) = \zeta'(x'_1, x'_2, \dots, x'_{n'})$ and vice versa. Thus solving LP is equivalent to LP'.

::: {.theorem #lp-equiv-to-standard-form}
Every linear program is equivalent to a linear program in the standard form.
:::

::: {.proof}
test
:::