# Bland's rule, Klee--Minty cube

## Bland's rule

A pivot where $x_e$ enters and $x_\ell$ leaves is said to be **degenerate** if $a_{\ell e} > 0$ and $b_\ell = 0$. 
In this case, as $b_{\ell}/a_{\ell e}$, the entering variables value remains unchanged at 0 even after it becomes basic. 
Similarly, the objective value also stays constant after the pivot. 
Degenerate simplices can cause the simplex algorithm to get stuck in an infinite loop. 
In linear programming, this issue is called **cycling**. 
For example, the following linear program 
```{r, cycling-lp, results = 'asis', echo = FALSE}
cycling_lp <- new_linear_program(
  obj = c(1, -2, 0, -2),
  A = matrix(c(
      1/2, -7/2, -2, 4, 
      1/2, -1, -1/2, 1/2,
      1, 0, 0, 0), nrow = 3, byrow = TRUE),
  b = c(0, 0, 1)
)

cat(str_math(cycling_lp))
```
cycles for the following pivot rules:

- $x_1$ enters and $x_5$ leaves,
- $x_2$ enters and $x_6$ leaves,
- $x_3$ enters and $x_1$ leaves,
- $x_4$ enters and $x_2$ leaves,
- $x_5$ enters and $x_3$ leaves,
- $x_6$ enters and $x_4$ leaves.

There are several ways to prevent cycling, the simplest of which is called **Bland's rule**, which states that whenever there are multiple candidates for the entering or leaving variables, choose the one with the **smallest index**. One can check that the sixth pivot in the above example violates Bland's rule. 

::: {.theorem}

Bland's rule prevent cycling. 

:::

The updated Phase II simplex algorithm that takes into account Bland's rule is as follows.
<div class="boxed">

1. *Find the entering variable:*
    1. Let $E$ be the set of indices $j$ such that $c_{j}$ is positive. 
        - **If $E$ is empty, exit.**
    2. Set $e = \min E$.
2. *Find the leaving variable:*
    1. Let $L$ be the set of indices $i$ such that $a_{ie}$ is positive.
        - **If $L$ is empty, exit. Linear program is unbounded with no optimal solution.**
    2. Set $\ell = \min \left[ \mathrm{arg}\min_{i \in L} \left(\dfrac{b_i}{a_{ie}}\right) \right]$.
3. *Pivot:*
    2. Add $x_e$ to the set of basic variables and remove it from the set of non-basic variables.
    3. Add $x_\ell$ to the set of non-basic variables and remove it from the set of basic variables.
    1. Rewrite the basic variables and the objective function in terms of the non-basic variables.
4. *Go back to step 1.*
</div>


## Klee--Minty cube 

The simplex algorithm runs in polynomial time over real-world problems but is an exponential time algorithm in the worst case.
The following is an example of a linear program in $n$ variables and $n$ constraints, called a Klee--Minty cube, for which the simplex method requires $\mathcal{O}(2^n)$ steps. 
One proves this by showing that the feasible set has $2^n$ vertices and the simplex algorithm visits all the vertices of the feasible set.

\begin{align}
  \begin{array}{rlllllllll}
    \mbox{maximize: }  & \sum \limits_{j = 1}^n x_j & \\
    \mbox{subject to: } & \sum \limits_{j = 1}^{i - 1} 2 x_j + x_i  & \le 2^{i - 1} & & \mbox{ for } i = 1, \dots, n.
  \end{array}
\end{align}